engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - php
      - javascript
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.php"
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
