engines:
  phpcodesniffer:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
  	enabled: false
    config:
    	languages:
      - php
      - javascript
ratings:
  paths:
  - "**.php"
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
