engines:
  rubocop:
    enabled: false
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  phpcodesniffer:
    enabled: true
  brakeman:
   	enabled: true
    #exclude_fingerprints:
    #- 08c185b3f764f262539a1f76997d3a89
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
  	enabled: true
    config:
    	languages:
      - ruby
      	#mass_threshold: 30
      - javascript
ratings:
  paths:
  - "**.php"
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
